Mediline.Web/src/components/Dashboard/Chatbox.jsx, Mediline.Web/src/views/routes/PatientAppointment.jsx, mediline.web/src/views/routes/FindADoctor.jsx, package-lock.json
incorporated chatbox window
slight modification to style of chat window
added ids to itemgroups in "findADoctor" page for use in UI testing
=> changes to appointment page for patient

Mediline.Web/src/components/Dashboard/Chatbox.jsx, Mediline.Web/src/components/Dashboard/SharedChatBox.jsx, Mediline.Web/src/components/General/CommonIcon.jsx, Mediline.Web/src/viewModels/Chatbox-axios.js, Mediline.Web/src/views/routes/DoctorAppointment.jsx, Mediline.Web/src/views/routes/PatientAppointment.jsx, mediline.web/package-lock.json, mediline.web/package.json
user can send messages which will appear in the chatbox
=> chatbox messages

mediline.web/src/viewModels/DashboardLayoutViewModel.js, mediline.web/src/views/routes/DDHome.jsx, mediline.web/src/views/routes/DDProfile.jsx
- Removed all hard-coded dependencies from Doctor Dashboard
- Temporarily keeping the dummy hard-coded data inside the Patient Profile Page
- Replaced any fields that could be populated immediately by data from the current user object in User Provider
=> Doctor Dashboard Layout

mediline.web/src/views/routes/DashboardLayout.jsx, mediline.web/src/views/routes/PHHome.jsx, mediline.web/src/views/routes/PHPatient.jsx, mediline.web/src/views/routes/login.jsx
- Removed all hard-coded data dependencies in the pharmacy dashboard
- No backend integration yet, just used generic hard-coded data that does not need IDs to display
=> Pharmacy Dashboard Layout

Mediline.Web/src/components/General/InputBar.jsx, mediline.web/src/viewModels/DashboardLayoutViewModel.js, mediline.web/src/viewModels/FindDoctorViewModel.js, mediline.web/src/views/routes/PDFindDoctor.jsx, mediline.web/src/views/routes/PDHome.jsx, mediline.web/src/views/routes/PDProfile.jsx
- Integrated the Find Doctor Page with the backend
- Page will only render when all data is fetched from the backend; if data cannot be fetched, loading screen is replaced with an error
- There is no endpoint for adding a doctor or for filtering by specialty or name (there is technically an endpoint for sorting by rating, but it is not the average rating but by the individual "stars" that the user gives the doctor)
- Rendering placeholder objects in place of missing data in the Patient Dashboard Homepage (I will revisit this page to copy over the loading screen logic from the Find Doctor Page since it will probably not work with real data in its current state since the app will synchronously render the component before the data is fetched and prepared)
- Rendering placeholder objects in …
=> Integrated Find Doctor Page

mediline.web/src/views/routes/PDFindDoctor.jsx
I fixed the Patient Dashboard Find Doctor page by removing a call to a function that I removed
=> Find Doctor Hotfix

mediline.web/src/viewModels/DashboardLayoutViewModel.js, mediline.web/src/viewModels/FindDoctorViewModel.js, mediline.web/src/viewModels/PDHomeViewModel.js, mediline.web/src/views/routes/FindADoctor.jsx, mediline.web/src/views/routes/PDHome.jsx
- Integrated the Find Doctor Guest View with the backend
- Made a separate view model that will fetch all of the data that the Patient Dashboard Home View will need
- Created a loading function for the Patient Dashboard Home View that will be used to refresh the data in the Patient Dashboard Home View whenever a successful POST request is submitted by the user
=> Find Doctor Guest View Integration + Patient Dashboard Home Refactor

mediline.web/src/viewModels/DiscussionForumViewModel.js, mediline.web/src/viewModels/PDHomeViewModel.js, mediline.web/src/views/routes/DiscussionForumPage.jsx, mediline.web/src/views/routes/PDHome.jsx
- Integrated the Discussion Forum Guest View with the backend (it is *very* slow to load because of how many API calls it makes but I will try optimizing it later by using Promise.all() to make concurrent API calls rather than sequential API calls)
- Discovered and fixed some issues with PDHome and the PDHomeViewModel (I added a valid export constant that PDHome can use)
=> Discussion Forum Guest

mediline.web/src/viewModels/FindDoctorViewModel.js, mediline.web/src/views/routes/PDHome.jsx
- Removed a dummy line that prevented PDHome from rendering
=> PDHome Login Fix

Mediline.Web/mediline.web.esproj, mediline.web/package-lock.json, mediline.web/package.json, mediline.web/src/views/routes/PDHome.jsx
- Deployment is failing because of a dependency that does not exist in the site (@rollup-linx-x64-gnu)
- I deleted the node_modules and package.lock.json file to clear out all the NPM packages and then rebuilt the app so that the NPM packages are reinstalled with the optional dependency
=> Installing optional depencies for deployment

mediline.web/mediline.web.esproj, package-lock.json, package.json
- Checked out an error that GitHub caught in main.jsx with a misnamed './Login' import and fixed it
=> Finding more errors that are preventing the app from deploying

mediline.web/src/viewModels/DashboardLayoutViewModel.js, mediline.web/src/viewModels/PHViewModel.js, mediline.web/src/views/routes/PHHome.jsx, mediline.web/src/views/routes/PHPatient.jsx
Didn't test new pharmacist account - probably need to add functionality to add stock
Didn't test patients that have pharmacy as main pharmacy
Didn't test new requests - don't have any
Doesn't implement accept/reject - not implemented in backend yet
=> Pharma MVP

mediline.web/package-lock.json, mediline.web/package.json, mediline.web/src/viewModels/OverviewViewModel.js, mediline.web/src/views/routes/PDHome.jsx, mediline.web/src/views/routes/PDProfile.jsx
- Integrated the Encounters Tab with the backend (still need to test for past appointments and might come back again later to add an appointment cancellation button)
- Added an "Add Regimen" button to the header of the Regimens tab so that a patient can always assign themselves exercises
- Refactored the Survey Form so it not only has a working submit button but also a submission function that creates a POST request to the backend (never checked if the POST request worked or whether it has all the required fields)
=> Encounters Tab Integration + Various Fixes for the Patient Profile Page

mediline.web/src/assets/js/api.js, mediline.web/src/assets/scss/components/_input.scss, mediline.web/src/assets/scss/utility/_utilities.scss, mediline.web/src/components/General/InputBar.jsx, mediline.web/src/viewModels/PHViewModel.js, mediline.web/src/views/routes/Home.jsx, mediline.web/src/views/routes/PHPatient.jsx, mediline.web/src/views/routes/Register.jsx, mediline.web/src/views/routes/RouteErrorPage.jsx
Some fixes to error handling pages, overhaul to input bars (not complete)
=> Register edit

mediline.web/src/components/General/InputBar.jsx, mediline.web/src/viewModels/DPViewModel.js, mediline.web/src/views/routes/DDHome.jsx, mediline.web/src/views/routes/DDProfile.jsx, mediline.web/src/views/routes/PDAppointment.jsx, mediline.web/src/views/routes/PDDiscussionForum.jsx, mediline.web/src/views/routes/PDHome.jsx, mediline.web/src/views/routes/PDProfile.jsx
What I implemented:
I am only missing the Regimens and Graphs tab, I will port those over from the Patient Profile Page even if they might be missing some functionality
- Added a functional "Generate Prescription" card but I think the logic I used to fetch active medications is wrong since the changes are not being displayed in the Medications Tab (or the pharmacist has yet to accept or reject the prescription if that is the way we are implementing the feature)
- Added a line of code to prevent patients from accessing the appointment room
What I plan to accomplish:
- Import the last two tabs for the Doctor Patient Profile View from Patient Profile View
- Maybe mess around with these two features and see if I can resolve some of Chris' issues (no promises however)
- I want to add a button …
=> Partially Integrated the Doctor Dashboard Profile Page

mediline.web/src/viewModels/DPViewModel.js, mediline.web/src/viewModels/DashboardLayoutViewModel.js, mediline.web/src/viewModels/DiscussionForumViewModel.js, mediline.web/src/viewModels/OverviewViewModel.js, mediline.web/src/views/routes/DDProfile.jsx, mediline.web/src/views/routes/PDProfile.jsx
- Contains null checks inside the DashboardLayoutViewModel and some additional ones added inside PDProfile
- Also contains various in-progress fixes for displaying appointment info (particularly for past appointments)
=> Null Error Fixes

mediline.web/src/viewModels/PDHomeViewModel.js, mediline.web/src/views/routes/PDHome.jsx
- PD Home _a lot_ more problems than I anticipated once we got data to display
- Removed/correct  _a lot_ of data that I was trying to extract which either were removed from the endpoint e.g. _payment status_ or being incorrectly fetched from inside the JSX itself
- Refactored the centralized data fetching function inside the view model to include active and past medications and to also attach appointment data so that it is not necessary to make API calls inside of the JSX
=> BIG FIX for PDHome

mediline.web/src/viewModels/FindDoctorViewModel.js, mediline.web/src/views/routes/FindADoctor.jsx
Fixed some formatting -- filters do not visually reset :(
=> Find doctor fix

mediline.web/src/viewModels/DPViewModel.js, mediline.web/src/viewModels/DashboardLayoutViewModel.js, mediline.web/src/views/routes/DDProfile.jsx, mediline.web/src/views/routes/PDProfile.jsx
- Used the most recently added patient with a lot of data to debug issues in the Patient and Doctor Dashboards
- Added null checking conditions to (most) things that I could immediately detect issues in
- Implemented conditional data fetching for forms and certain tabs (might come back and implement conditional data fetching for all tabs so that no data is left unused)
=> Hunt for NULL value errors/fixing display

mediline.web/src/viewModels/DPViewModel.js, mediline.web/src/viewModels/FindDoctorViewModel.js, mediline.web/src/viewModels/PDHomeViewModel.js, mediline.web/src/views/routes/DDAccount.jsx, mediline.web/src/views/routes/DashboardLayout.jsx, mediline.web/src/views/routes/PDFindDoctor.jsx, mediline.web/src/views/routes/PDHome.jsx, mediline.web/src/views/routes/PDProfile.jsx
- Included multiple fixes where instances of currentUser are replaced with the updated user obejct returned by the centralized data fetching function
- Added an accepting patients field into the doctor info update form
- Made sure the changes made by Add Doctor are loaded in before navigating back into the dashboard
=> Data Update

mediline.web/src/components/Dashboard/Chatbox.jsx, mediline.web/src/views/routes/PDAppointment.jsx
End Appointment Flow Working
next is post appointment flow
=> After appointment
